### ISSUE TITLE
"The application did not respond"

### ISSUE THREAD

**Issue by Dense-User-Jr** [tedztar/mcstatusbot#212]
Unable to access any of the bot's commands, instead being prompted with "The application did not respond". Removing and readding the bot did not solve the issue. I'm not sure if/where I can see if the bot is actually online or not, so it's very possible that the bot's just offline and I can't tell.

**Comment by RahulR100** [comment]
Hey! Thanks for the heads up, looks like the bot had indeed gone offline into a "zombie" state where the bot is active but discord closes the websocket connection to our bot. Looking through the logs I can see that the heartbeat system is trying to restart the shards but even after they restart it does not fix anything. I can also see that the issue persists across all shards.

This is most likely a networking issue and we are looking into it now. I'll keep you posted when we find the cause and apply a fix. I also plan to add a proper uptime monitor so that all of you and myself can see when the bot is offline and when it is not - most likely in the May update.
